Alfresco pr
ArkCase/ark_alfresco pull request #1
Opened 2021-07-19 23:27 UTC by ymuwakki

2021-07-21 07:37 UTC, fabricetriboix commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
@JonHolman I would prefer our S3 bucket to hold the vanilla artifacts as released by the various vendors/projects. Otherwise, we will have to setup a new process to manage those modifications.

2021-07-21 07:37 UTC, fabricetriboix commented on Dockerfile
> +#   yum clean all && \
I agree

2021-07-23 14:27 UTC, JonHolman commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
@fabricetriboix I understand your point, but should our Dockerfile be modifying files?  It's not like these are dynamic edits that are not known until container build time, these are exact hardcoded edits.  So why should they be occurring in our Dockerfile.

Perhaps we should have a team conversation on this as its bigger than this one image/pr.  For my samba image the artifacts will not be from the vendor.  My starting artifact is the built samba with dependencies that @jdshinnick created for me.  I told him we need to document that process as that's the downside to doing that.  It was a very good point from @ymuwakki that I was initially trying to do way too much in the Dockerfile building all of samba and its dependencies.

2021-07-23 15:35 UTC, fabricetriboix commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
@JonHolman My preference would be for the Dockerfile to be as self-contained as possible, but of course this is open for discussion.

2021-07-23 18:48 UTC, JonHolman commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
@fabricetriboix  I agree about the Dockerfiles being as self contained as possible, but if we're pulling in an artifact that we know is not how we want it and we always do the exact same transform on it, couldn't we just change the file we're hosting?   I also like keeping our files (Dockerfiles, scripts, etc) clean and simple and personally I don't find sed to be all that readable.  Like to get other opinions on this:
@drivera-armedia @jdshinnick @david-oc-miller

2021-07-23 19:41 UTC, fabricetriboix commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
@JonHolman If we need to customize a vanilla package, it has to do done somewhere. It could be in the Dockerfile, or it could be a script in a CI/CD pipeline that periodically fetches the vanilla package, apply the modifications and upload the modified package to S3. Or it could even be a manual task. There are pros and cons for each approach. Ideally, though, I think such processes should be automated as far as possible. I agree with you that sed is quite obscure, and more importantly it is a very crude tool that might not do what you think it does.

2021-07-26 20:34 UTC, drivera-armedia commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
Far be it from me to insert myself into a discussion I've not been invited to, but I'm going to insert myself into a discussion I've not been invited to :)

So ... in my mind we should stay away from deep, complex SED blocks unless there is 100% no other way to carry out the requisite editions more simply or cleanly. For instance: if we know that there are XML files that need to be edited repeatedly, perhaps templates are a better approach? Also, there are other tools like xmlstarlet that allow direct, in-place edition of XML using XPath rules to select the nodes, and perform literally _**any**_ modification desired upon those nodes.

Furthermore, if the changes to be applied are static, we're better off doing them manually and letting the modified file become the new, default file. Doing in-line SED edition is sensible if and only if we cannot predict the values to be used in substitution ahead of time. If we can, then we definitely should instead resort to using our own customized files and substituting them in place, wholesale.

2021-07-26 20:46 UTC, drivera-armedia commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
I would also argue that resorting to these changes when the outcome is static (i.e. not parameterized) serves little if any purpose given the fact that if a new version comes out, it's entirely likely those edits will have to be reviewed to see if they still apply in the same way or if they need changing.

Therefore, if you're having to do the legwork anyway, might as well do it all (edit the file statically), and use the updated file alongside the Dockerfile, vs. trying to have the edition work for _**every**_ possible version - which may not be viable.

2021-07-28 19:24 UTC, ymuwakki commented on Dockerfile
> +ARG CENTOS_MAJOR=7
fixed

2021-07-28 19:24 UTC, ymuwakki commented on Dockerfile
> +RUN set -eux; \
fixed

2021-08-19 07:04 UTC, fabricetriboix commented on Dockerfile
> +ENV CATALINA_HOME /usr/local/tomcat
@JonHolman I am happier with `/app`, yes

2021-08-19 07:07 UTC, fabricetriboix commented on Dockerfile
> +ADD  https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz /tmp
@JonHolman I think we now agreed to download artifacts directly from the original source, isn't it?

2021-08-19 07:27 UTC, fabricetriboix commented on Dockerfile
> +    sed -i "s/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"/\  <Listener\ className=\"org.apache.catalina.startup.VersionLoggerListener\"\ logArgs=\"false\"/g" /usr/lo
As discussed in a meeting earlier this week, we decided that our Docker containers should be parameterized using environment variables as far as practically possible. If it requires modifying configuration files, that will be the job of a startup script. So I will mark this conversation as resolved.

2021-08-19 07:30 UTC, fabricetriboix requested changes
This repository is 162M in size. I suspect some artifacts have been committed at some point... I would suggest to remove those commits if possible (I don't know enough about git/github to know whether it is possible or not), otherwise to delete and recreate this repo afresh.

Also, the `artifacts` directory should not be committed into github. It's very purpose is to have artifacts in S3 rather than in github.

2021-08-19 14:12 UTC, JonHolman commented on Dockerfile
> +ADD  https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz /tmp
@fabricetriboix  yes, that's what we've agreed on.  I would like to think I made the comment above before we agreed on that.

2021-08-19 23:20 UTC, ymuwakki commented on get-artifacts.sh
> +aws s3 cp s3://arkcase-container-artifacts/ark_alfresco ./ --recursive --profile ark-cli
all artifacts are downloaded from nexus internet website so no more script and no more S3 bucket

2021-08-20 01:10 UTC, ymuwakki commented on Dockerfile
> +FROM centos:$CENTOS_MAJOR
yes, updated.

2021-08-20 01:11 UTC, ymuwakki commented on Dockerfile
> +#   yum clean all && \
Ok. removed.

2021-08-20 01:17 UTC, ymuwakki commented on Dockerfile
> +    find ./bin/ -name '*.sh' -exec sed -ri 's|^#!/bin/sh$|#!/usr/bin/env bash|' '{}' + && \
According to that bug I assume so.  Bash handles env vars with periods better than sh.  So replacing all scripts to run in bash instead of sh.

2021-08-20 01:20 UTC, ymuwakki commented on Dockerfile
> +RUN sed -i "s/shared.loader=/shared.loader=\${catalina.base}\/shared\/classes/" ${TOMCAT_DIR}/conf/catalina.properties && \
What about upgrades and stuff? Its easier to just update the file using sed.  In this case its changing the path of the shared.loader in the catalina.properties.  II like sed since its been around for 25 years and supports regex so I am comfortable with it.

2021-08-20 01:20 UTC, ymuwakki commented on Dockerfile
> +    sed -i -e "\$a\grant\ codeBase\ \"file:\$\{catalina.base\}\/webapps\/alfresco\/-\" \{\n\    permission\ java.security.AllPermission\;\n\};\ngrant\ codeBase\ \"file:\$\{catalina.base\}\/webapps\/R
see reply above

2021-08-20 01:22 UTC, ymuwakki commented
Code has been updated a lot so maybe we should do another PR.

2021-08-20 01:22 UTC, closed without merging