Alfresco pr
ArkCase/ark_alfresco pull request #2
Opened 2021-08-20 01:31 UTC by ymuwakki

I am using sed for updating 4 files for the following reasons:
1. used for very basic end of line appending and pattern replacement
2. supports upgrades
3. provided, tested, and maintained by vendor, Alfresco.

2021-08-20 07:30 UTC, fabricetriboix requested changes
Please make sure no logs are stored inside the container. I am actually very interested to know how to do that because for Snowbound, I tried to configure Tomcat not to log anything inside the container, but it still is...

2021-08-20 07:30 UTC, fabricetriboix commented on Dockerfile
> +    yum clean all && \
Maybe just do a single `yum clean all` at the end?

2021-08-20 07:30 UTC, fabricetriboix commented on Dockerfile
> +RUN mkdir -p "$CATALINA_HOME"
WORKDIR creates the directory if in doesn't exist, so you can remove the `RUN mkdir -p "$CATALINA_HOME"` command

2021-08-20 07:30 UTC, fabricetriboix commented on Dockerfile
> +    chmod 777 logs work ; \
The `logs` directory should not exist, and Tomcat should be configured such that no logs are written inside the container.

2021-08-20 07:30 UTC, fabricetriboix commented on Dockerfile
> +WORKDIR ${TOMCAT_DIR}
This is the same as the previous `WORKDIR ${CATALINA_HOME}` command, because CATALINA_HOME and TOMCAT_DIR have the same value.

2021-08-20 07:30 UTC, fabricetriboix commented on Dockerfile
> +        ${TOMCAT_DIR}/webapps/alfresco/WEB-INF/classes/log4j.properties && \
log4j should be configured to log only to stdout, not to any log file

2021-08-20 07:30 UTC, fabricetriboix commented on Dockerfile
> +#EXPOSE 10001
Please remove commented code

2021-08-20 07:30 UTC, fabricetriboix commented on artifacts/alfresco-global.properties
> +jodconverter.enabled=false
Please replace CRLF line ending (i.e. Windows line ending) with LF only (i.e. UNIX line ending).

2021-08-20 07:30 UTC, fabricetriboix commented on docker-compose.yaml
> +            JAVA_TOOL_OPTIONS: "
The quotes make the code very strange and difficult to read. Maybe you could use `>`, eg:

```
JAVA_TOOL_OPTIONS: >
  -Dxyz=abc
  etc...
```

2021-08-20 07:30 UTC, fabricetriboix commented on docker-compose.yaml
> +                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
From the point of view of Alfresco, all traffic will be unencrypted. TLS will be managed by Istio via the Envoy proxy. Can we remove all references to TLS in this container?

2021-08-20 07:30 UTC, fabricetriboix commented on docker-compose.yaml
> +            JAVA_OPTS: "
Ditto: please consider using `>` inside of those weird quotes

2021-08-20 12:50 UTC, fabricetriboix commented on docker-compose.yaml
> +        image: alfresco/alfresco-content-repository-community:acs
We can't use docker-compose to build or run the `ark_alfresco` image. Is that intentional?

2021-08-20 17:54 UTC, ymuwakki commented on Dockerfile
> +RUN mkdir -p "$CATALINA_HOME"
ok.

2021-08-20 17:54 UTC, ymuwakki commented on Dockerfile
> +    yum clean all && \
ok

2021-08-20 17:56 UTC, ymuwakki commented on Dockerfile
> +    chmod 777 logs work ; \
I dont know how to do that. So I cannot support your request,

2021-08-20 17:57 UTC, ymuwakki commented on Dockerfile
> +WORKDIR ${TOMCAT_DIR}
yes, trying to keep each "step" separate so if we go in circles again we can always strip the code into a separate dockerfile.

2021-08-20 17:57 UTC, ymuwakki commented on Dockerfile
> +#EXPOSE 10001
ok

2021-08-20 17:58 UTC, ymuwakki commented on docker-compose.yaml
> +            JAVA_TOOL_OPTIONS: "
I dont understand. Pls elaborate on your solution

2021-08-20 17:59 UTC, ymuwakki commented on docker-compose.yaml
> +                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
The keystore is not only used for TLS, but also for encrypting keys so its an Alfresco requirement on startup.  This cannot be removed.

2021-08-20 17:59 UTC, ymuwakki commented on docker-compose.yaml
> +            JAVA_OPTS: "
I have never used > - maybe a quick call to explain?

2021-08-20 18:00 UTC, ymuwakki commented on docker-compose.yaml
> +        image: alfresco/alfresco-content-repository-community:acs
Why? I use it for unit testing and it works fine.

2021-08-20 18:01 UTC, ymuwakki commented on artifacts/alfresco-global.properties
> +jodconverter.enabled=false
ok

2021-08-23 08:22 UTC, fabricetriboix commented on Dockerfile
> +WORKDIR ${TOMCAT_DIR}
Fair enough

2021-08-23 08:25 UTC, fabricetriboix commented on docker-compose.yaml
> +            JAVA_TOOL_OPTIONS: "
Instead of writing this:

```
  environment:
    JAVA_TOOL_OPTIONS: "
      -Dencryption.keystore.type=JCEKS
      etc...
      "
```

Write this:

```
  environment:
    JAVA_TOOL_OPTIONS: >
      -Dencryption.keystore.type=JCEKS
      etc...
```

The `>` means "remove all the line endings in the next block". So the end result is the same as this:

```
  environment:
    JAVA_TOOL_OPTIONS: -Dencryption.keystore.type=JCEKS etc...
```

2021-08-23 08:25 UTC, fabricetriboix commented on docker-compose.yaml
> +                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
All right, thanks

2021-08-23 08:27 UTC, fabricetriboix commented on docker-compose.yaml
> +        image: alfresco/alfresco-content-repository-community:acs
To unit test what? If you want to unit test your `ark_alfresco` image, I would expect something like 

```
  build:
    context: .
```

In the `alfresco` service in the docker-compose.yaml file

2021-08-24 17:28 UTC, ymuwakki commented on docker-compose.yaml
> +            JAVA_TOOL_OPTIONS: "
@fabricetriboix  I had to use >- to enable "No newline at end (strip)" to make this work.  So instead of ">", need to use ">-"

2021-08-24 17:29 UTC, ymuwakki commented on docker-compose.yaml
> +            JAVA_OPTS: "
I had to use >- to enable "No newline at end (strip)" to make this work. So instead of ">", need to use ">-"

2021-08-24 20:52 UTC, JonHolman commented on artifacts/alfresco-global.properties
> +activities.post.lookup.cronExpression=0 0 0 ? * * 2099
2099?

2021-08-24 20:52 UTC, JonHolman commented on Dockerfile
> +    chmod o-w ${TOMCAT_DIR}/work && \
Would it be more readable to comma separate these on one line as:

`
chmod g+rwx,o-w ${TOMCAT_DIR}/work && \
`

2021-08-24 20:52 UTC, JonHolman commented on Dockerfile
> +    sed -i -e "\$a\grant\ codeBase\ \"file:\$\{catalina.base\}\/webapps\/alfresco\/-\" \{\n\    permission\ java.security.AllPermission\;\n\};\ngrant\ codeBase\ \"file:\$\{catalina.base\}\/webapps\/R
Why are we doing this?  Could we not just have a catalina.policy in the repo and copy it in?

2021-08-24 20:52 UTC, JonHolman commented on Dockerfile
> +    sed -i -e "s_log4j.appender.File.File\=alfresco.log_log4j.appender.File.File\=${TOMCAT_DIR}/logs\/alfresco.log_" \
Why are we doing this?  Could we not have a log4j.properties the way we want it in the repo and copy it in?

2021-08-24 20:52 UTC, JonHolman commented on Dockerfile
> +RUN sed -i "s/shared.loader=/shared.loader=\${catalina.base}\/shared\/classes/" ${TOMCAT_DIR}/conf/catalina.properties && \
Why are we doing this? Could we not have a catalina.properties the way we want it in the repo and copy it in?

2021-08-24 20:54 UTC, ymuwakki commented on artifacts/alfresco-global.properties
> +activities.post.lookup.cronExpression=0 0 0 ? * * 2099
essentially disabling those jobs

2021-08-24 20:55 UTC, ymuwakki commented on Dockerfile
> +    sed -i -e "\$a\grant\ codeBase\ \"file:\$\{catalina.base\}\/webapps\/alfresco\/-\" \{\n\    permission\ java.security.AllPermission\;\n\};\ngrant\ codeBase\ \"file:\$\{catalina.base\}\/webapps\/R
I am using sed for updating 4 files for the following reasons:

used for very basic end of line appending and pattern replacement
supports upgrades
provided, tested, and maintained by vendor, Alfresco.

2021-08-24 20:55 UTC, ymuwakki commented on Dockerfile
> +    sed -i -e "s_log4j.appender.File.File\=alfresco.log_log4j.appender.File.File\=${TOMCAT_DIR}/logs\/alfresco.log_" \
I am using sed for updating 4 files for the following reasons:

used for very basic end of line appending and pattern replacement
supports upgrades
provided, tested, and maintained by vendor, Alfresco.

2021-08-24 20:56 UTC, ymuwakki commented on Dockerfile
> +RUN sed -i "s/shared.loader=/shared.loader=\${catalina.base}\/shared\/classes/" ${TOMCAT_DIR}/conf/catalina.properties && \
I am using sed for updating 4 files for the following reasons:

used for very basic end of line appending and pattern replacement
supports upgrades
provided, tested, and maintained by vendor, Alfresco.

2021-08-24 20:56 UTC, ymuwakki commented on Dockerfile
> +    chmod o-w ${TOMCAT_DIR}/work && \
If that works, sure, easier to read.

2021-08-25 08:49 UTC, naveen-armedia approved these changes

2021-08-25 09:23 UTC, fabricetriboix commented on artifacts/alfresco-global.properties
> +activities.post.lookup.cronExpression=0 0 0 ? * * 2099
@ymuwakki Please use LF for line endings, not CRLF

2021-08-25 13:45 UTC, ymuwakki commented on artifacts/alfresco-global.properties
> +activities.post.lookup.cronExpression=0 0 0 ? * * 2099
yes, updated to remove CRLF

2021-08-25 13:46 UTC, ymuwakki commented on Dockerfile
> +        ${TOMCAT_DIR}/webapps/alfresco/WEB-INF/classes/log4j.properties && \
ok. updated log4j.properties and logging.properties to remove output to file and only to console

2021-08-25 13:50 UTC, naveen-armedia submitted a review, later dismissed

2021-08-25 13:55 UTC, fabricetriboix approved these changes

2021-08-25 13:55 UTC, fabricetriboix commented on docker-compose.yaml
> +            JAVA_OPTS: "
It would be good to use `>` everywhere relevant, but that's a minor point so I will approve the PR

2021-08-25 13:59 UTC, naveen-armedia approved these changes

2021-08-25 14:04 UTC, merged